---
- name: Configure Server
  become: yes
  copy:
    src: config-script.sh
    dest: /home/ubuntu/config-script.sh
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0774

- name: Execute configuration script
  become: yes
  become_method: sudo
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_PORT: 5432
    TYPEORM_HOST: TYPEORM_HOST_STRING
    TYPEORM_USERNAME: TYPEORM_USERNAME_STRING
    TYPEORM_PASSWORD: TYPEORM_PASSWORD_STRING
    TYPEORM_DATABASE: TYPEORM_DATABASE_STRING
  shell:
    /home/ubuntu/config-script.sh